### ISSUE TITLE
Добавь Changelog

### ISSUE THREAD

**Issue by 3fbaea00** [Nekiplay/MacrosAPI-v3#1]
Добавь список изменений, что апдейтнул то и почему теперь v3

**Comment by Nekiplay** [comment]
В v3 были исправлены ошибки при использования одного MacrosUpdater и MacrosManager теперь не нужно под каждый скрипт создавать свой MacrosUpdater и MacrosManager

Так-же были улучшены ивенты получения объектов от макроса клиенту и наоборот

**Comment by 3fbaea00** [comment]
"В v3 были исправлены ошибки" - Cмысл тогда делать уже v3?

"при использования одного MacrosUpdater и MacrosManager теперь не нужно под каждый скрипт создавать свой MacrosUpdater и MacrosManager" - Через Task Queue реализовал?

**Comment by 3fbaea00** [comment]
Вероятно это невозможно, но можешь как-то сделать, чтобы в дебаге макроса пк не забирало управление.
Думаю как минимум через изменение мода [перехват -> чтение] возможно реализовать такое, только тогда нужно будет переписывать враппер апи. (Мод кстати можно сделать принудительно [чтение] при дебаге)

**Comment by 3fbaea00** [comment]
Может ещё реализовать как отдельный процесс, а перехват осуществлять через ссылку на bool?, а не return bool.
Если метод определённое время не возвращает значение - принудительно возвращать false(не отклонять действие)
Так хотя бы дебаг можно будет оффнуть, хоть и с лютыми лагами

**Comment by Nekiplay** [comment]
Чтобы не блокало управление в дебаге не буду делать скорее всего

**Comment by Nekiplay** [comment]
Да и отдельный процесс это минус для проверок от SS

**Comment by Nekiplay** [comment]
> Может ещё реализовать как отдельный процесс, а перехват осуществлять через ссылку на bool?, а не return bool. Если метод определённое время не возвращает значение - принудительно возвращать false(не отклонять действие) Так хотя бы дебаг можно будет оффнуть, хоть и с лютыми лагами

Можно использовать try catch и UnloadMacros или macroManager.Quit
